name: SSH deploy on push
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run composer install
        run: |
          composer install --no-interaction --optimize-autoloader
      - name: NPM
        run: |
          npm install
          npm run build

      - name: rsync deploy
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --exclude-from=.rsyncignore
          path: .
          remote_host: ${{secrets.REMOTE_HOST}}
          remote_port: ${{secrets.REMOTE_PORT}}
          remote_user: ${{secrets.REMOTE_USER}}
          remote_key: ${{secrets.REMOTE_KEY}}
          remote_key_pass: ${{ secrets.REMOTE_PASSPHRASE }}
          remote_path: ${{secrets.REMOTE_PATH}}
      - name: Debug and Setup Project on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          passphrase: ${{ secrets.REMOTE_PASSPHRASE }}
          script: |
            cd ${{ secrets.REMOTE_PATH }}
            docker exec ms-php83 composer install
            docker exec ms-php83 php artisan storage:link
